timezone: Europe/London
encoding: UTF-8
permalink: /:title/
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude
exclude: [css/style.css.map, css/style.scss]

# SEO
title: Mariusz Zarzycki
description: A freelance web developer with a focus on always learning
url: https://vallode.cf/
author: Mariusz Zarzycki
twitter:
  username: Vallode_
logo: /images/favicon.png